/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab24.ankit.group01.a2;

public class App {

    private UserManager userManager;

    public App () {
        this.userManager = new UserManager();
        run();
    }

    public static void main(String[] args) {
        // running the App
        App app = new App();
    }

    public void run() {
        // displaying login screen
        Login login = new Login();
        login.displayLoginScreen();
        userManager = login.getUserManager();

    }
}