/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab24.ankit.group01.a2;

public class App {

    private UserManager userManager;

    public App () {
        this.userManager = new UserManager();
    }

    public static void main(String[] args) {

        // creating App
        App app = new App();

        // displaying login screen
        userManager.loginSystem();
        Login login = new Login();
        login.displayLoginScreen();
        this.user = login.getUser();

        // displaying main menu
        MainMenu mainMenu = new MainMenu();
        mainMenu.displayMainMenu();
        this.user = mainMenu.getUser();

    }
}