/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab24.ankit.group01.a2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void setting_up() {
        assertTrue(true);
    }
}
